### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by kishorekumar1505028** [pawanjenu/LeetcodeSessionManager#4]
**Describe the bug**
The extension is not working when I open a new session in incognito window.

**To Reproduce**
1. activate a new session in the browsers
2. activate a new session in incognito mode
3. step 2 fails as the active session 1 doesn't change

**Expected behavior**
The session should be changed in the incognito mode

**Screenshots**

**Additional context**

**Comment by pawanjenu** [comment]
@kishorekumar1505028 , thanks for reporting the Bug. 

This is because as mentioned in the chrome Dev Docs, incognito/private browsing windows will not retain local / session storage. Therefore when you open a new incognito mode. it's a new session altogether.

**Comment by teafoot** [comment]
@pawanjenu  i get anonymous session when i log in, is that normal?
