### ISSUE TITLE
LeetcodeSessionManager is removed from addons.mozilla.org

### ISSUE THREAD

**Issue by venkatraman-arumugam** [pawanjenu/LeetcodeSessionManager#5]
Kudos for developing the addon. This add-on really saves time. And I would be grateful if you could resurrect LeetcodeSessionManager 
LeetcodeSessionManager removed from addons.mozilla.org .

![image](https://user-images.githubusercontent.com/12130344/174155008-f402491f-8e4f-49d1-b396-2cf5e3cb2853.png)

**Comment by pawanjenu** [comment]
thanks for letting me know, will work on enabling it on Firfox.

**Comment by pawanjenu** [comment]
the issue has been fixed @venkatraman-arumugam . 
please confirm and close the ticket.

**Comment by venkatraman-arumugam** [comment]
hey @pawanjenu  thanks for fixing

**Comment by pawanjenu** [comment]
Would appreciate @venkatraman-arumugam if you could buy me a coffee 😊. 
and contribution’s appreciated😊.
