### ISSUE TITLE
Still not able to submit parallely

### ISSUE THREAD

**Issue by ACprime96** [pawanjenu/LeetcodeSessionManager#6]
When two devices working on the same problem submit the LC question, both submissions get logged to the same session.

**To Reproduce**
1. select respective LC session
2. submit the problem
3. go to LC sessions 
4. you will see only one session will get submissions other sessions don't get updated

**Expected behavior**
On submission, individual sessions should get updated parallelly

**Comment by pawanjenu** [comment]
@ACprime96 , is the session name being chosen differently in 2 devices same, or does it have different names?
ideally, if 2 people(from 2 devices) are working on a problem, it is expected to choose 2 different sessions.

**Comment by pawanjenu** [comment]
here are the steps i tested. 
device A:
- choose session **Test1**
- open problem A, hit submit

parallely on Device B:
- choose session **Test2**
- open problem A, hit submit. 

both Test1, Test2 sessions were updated with 1 problem as submitted.

**Comment by ACprime96** [comment]
Hey Pawan,
 We followed the exact same steps.
Will upload the drive link of a video demonstrating it.

Thanks and best regards,
Aditya

**Comment by pawanjenu** [comment]
that would help, thanks
